export const comments = [
  {
    id: "c1",
    text: "Félicitations docteur ! Une avancée remarquable pour la médecine préventive 👏",
    createdAt: "2025-10-17T08:30:00Z",
    likes: 8,
    user: {
      name: "Dr. Houssem Ben Salem",
      title: "Cardiologue",
      role: "Spécialiste en maladies cardiovasculaires",
      avatar: "https://randomuser.me/api/portraits/men/50.jpg",
    },
  },
  {
    id: "c2",
    text: "Un travail exceptionnel, la recherche médicale tunisienne avance à grands pas 🔬🇹🇳",
    createdAt: "2025-10-17T07:45:00Z",
    likes: 5,
    user: {
      name: "Dr. Amira Gharbi",
      title: "Chercheuse",
      role: "Biologiste médicale",
      avatar: "https://randomuser.me/api/portraits/women/64.jpg",
    },
  },
  {
    id: "c3",
    text: "Bravo à toute l’équipe du service d’oncologie pour cette réussite 🎗️",
    createdAt: "2025-10-16T16:10:00Z",
    likes: 6,
    user: {
      name: "Dr. Fares Kammoun",
      title: "Oncologue",
      role: "Chef de service",
      avatar: "https://randomuser.me/api/portraits/men/30.jpg",
    },
  },
  {
    id: "c4",
    text: "Une belle innovation technologique au service des patients 👩‍⚕️💡",
    createdAt: "2025-10-16T14:20:00Z",
    likes: 4,
    user: {
      name: "Dr. Sara Mbarek",
      title: "Médecin urgentiste",
      role: "Service des urgences CHU Sousse",
      avatar: "https://randomuser.me/api/portraits/women/45.jpg",
    },
  },
  {
    id: "c5",
    text: "Très inspirant ! La digitalisation du dossier médical change la donne 🧠💻",
    createdAt: "2025-10-16T12:55:00Z",
    likes: 3,
    user: {
      name: "Dr. Nidhal Ayari",
      title: "Radiologue",
      role: "Imagerie médicale",
      avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    },
  },
  {
    id: "c6",
    text: "Un pas de plus vers une médecine plus humaine et connectée ❤️",
    createdAt: "2025-10-15T18:40:00Z",
    likes: 7,
    user: {
      name: "Dr. Ons Boughzala",
      title: "Pédiatre",
      role: "Spécialiste en santé infantile",
      avatar: "https://randomuser.me/api/portraits/women/36.jpg",
    },
  },
  {
    id: "c7",
    text: "Excellent travail sur la gestion des données patients. Bravo l’équipe 👏📊",
    createdAt: "2025-10-15T17:15:00Z",
    likes: 5,
    user: {
      name: "Dr. Mehdi Charfi",
      title: "Infirmier coordinateur",
      role: "Service de soins intensifs",
      avatar: "https://randomuser.me/api/portraits/men/47.jpg",
    },
  },
  {
    id: "c8",
    text: "C’est encourageant de voir l’intelligence artificielle au cœur de la médecine moderne 🤖🩺",
    createdAt: "2025-10-15T15:00:00Z",
    likes: 9,
    user: {
      name: "Dr. Maryem Bouhallela",
      title: "Chercheuse",
      role: "Spécialiste en IA médicale",
      avatar: "https://randomuser.me/api/portraits/women/29.jpg",
    },
  },
  {
    id: "c9",
    text: "Très fier de cette collaboration interdisciplinaire entre médecins et ingénieurs 💪",
    createdAt: "2025-10-14T09:45:00Z",
    likes: 6,
    user: {
      name: "Dr. Khaled Karray",
      title: "Chirurgien",
      role: "Clinique Ibn Sina",
      avatar: "https://randomuser.me/api/portraits/men/14.jpg",
    },
  },
  {
    id: "c10",
    text: "Bravo à toute l’équipe Medilink pour cette avancée technologique au service des patients 🏥✨",
    createdAt: "2025-10-14T08:30:00Z",
    likes: 10,
    user: {
      name: "Dr. Sarra Kadraoui",
      title: "Interne en Médecine",
      role: "MERN Stack Developer - Medilink Project",
      avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    },
  },
];